plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

include:
  - MetricsLectureNotes.md

markdown: kramdown

kramdown:
  math_engine: katex
  syntax_highlighter_opts:
    block:
      line_numbers: true
